### PR TITLE
more changes related to test mode.

### PR DESCRIPTION
**Pull request by vixie**
1. add -4 and -6 options to limit resolver transport and types queried.
2. make it possible to specify more than one URL, no change to default.
3. add -r to preload libcurl's DNS cache via CURLOPT_RESOLVE.
4. reorganize argument/option parsing logic.
5. split some source lines that were longer than 80 columns.
6. change -t (test mode) to stop on first successful probe.

### CODE REVIEW

**Comment by bagder** [comment]
This looks good. I'm thinking we can actually allow multiple URLs even for "normal" lookups, to probe multiple servers at once - but we can deal with that separately.

But when doing the test mode on multiple URLs, don't you also want to know *which* servers that worked or nor worked now that you can specify a set?

**Comment by vixie** [comment]
On Wednesday, 25 September 2019 06:09:15 UTC Daniel Stenberg wrote:
> This looks good. I'm thinking we can actually allow multiple URLs even for
> "normal" lookups, to probe multiple servers at once - but we can deal with
> that separately.

i think it's going to be a challenge to present multiple outputs in a useful 
way. perhaps

[url]
   results
[url]
   results

> But when doing the test mode on multiple URLs, don't you also want to know
> *which* servers that worked or nor worked now that you can specify a set?

for my use case i only need to know if any of the URL's works. but i'll be 
happy to revise the patch to add a "-1" CLI option to make it stop on the 
first success, and otherwise, try them all.

i've gotten so much use out of libcurl over the years, that i am very happy to 
finally be able to give something back. let me know how you want to proceed.

-- 
Paul

**Comment by bagder** [comment]
I thought about it a little more but I now think we rather land your change as-is and if we want functionality as I mentioned then we work on that separately when someone wants that to happen. No need to overdo it now. Merge pending!

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
