### PR TITLE
Add "DOH!" sound

### PR DESCRIPTION
**Pull request by kimbo**
This adds a target to the Makefile called `with-sound` that builds sound support for doh that can be activated with the `-s` flag.

Example usage:
```
./doh -s example.com
```
The textual output should be identical to `./doh example.com`. Other than that, just make sure your volume isn't too high :smirk: 

If you prefer that to be the default behavior, you can always set an alias for it
(e.g. `alias doh="doh -s"`)

By default, doh sound support will not be included (meaning this won't affect people who don't know about it or want it).

As a side note, I tried finding a cross-platform lib to play audio and SDL2 was the best I could come up with. It seems kinda overkill given the use case, but it's what I found. I'm open to other (better) ideas if they're out there.

### CODE REVIEW

**Comment by kimbo** [comment]
@bagder Any word on this?

**Comment by bagder** [comment]
I've been struggling on what to think about this PR and how to proceed.

I don't want to be a party pooper and this is only conditional and I realize it is made with good intentions and the right spirit. At the same time, I fear that accepting this PR signals that this is a joke tool and that we'll get further jokes and will get to argue about why the next joke won't be merged when this was fine.

Right now, I'm leaning towards saying this was a fun idea and to reject it, but I'm also open to hearing if there are other voices out there that can convince me to accept it. So I rather just leave this open for now without making a firm decision. I'll tweet about it and see if I can drum up some opinions...

**Comment by kimbo** [comment]
That's fair. I made it purely for fun, and it's not really "useful" other than for humor, so I don't have a problem if you decide to close/reject it :+1:

(But it is pretty fun)

**Comment by Johannestegner** [comment]
We need this, I can't use curl if I have no doh!

**Comment by jay** [comment]
It's unnecessary. I don't get the struggle. It may actually be useful to someone and not a joke but that's besides the point. Every feature that's added has a maintenance cost and a maintenance cost is a time cost. Is this really worth your time? Is it really worth it to hear Homer Simpson say doh? (I somewhat suspect this argument may backfire, but ok). It's a cool idea and I liked reading about it but not for upstream.

**Comment by eloydegen** [comment]
@kimbo Please fork the repo and let it be packaged under the name `audioh`

**Comment by bagder** [comment]
Thanks everyone for your feedback, thoughts and comments and thanks to @kimbo for the PR. In the end I want to focus on code stability and include code that is easy to maintain - thus I say thanks but no thanks to this doh sound PR.

**Pull request closed without merging**
